# Generated by Django 3.1.3 on 2021-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_complainant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainant',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='complainant',
            name='password',
            field=models.CharField(default='123', max_length=300),
        ),
    ]
