# Generated by Django 3.1.3 on 2021-02-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210214_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crimeName', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('punishment', models.TextField(max_length=1000)),
            ],
        ),
    ]
