# Generated by Django 3.1.3 on 2021-02-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='chapter',
            field=models.CharField(default='', max_length=50),
        ),
    ]
